import Providers from './Providers';
import './global.css';
import { ReactNode } from 'react';

export const metadata = {
  title: 'Welcome to greca-front',
  description: 'Generated by create-nx-workspace',
};

const RootLayout = ({ children }: { children: ReactNode }) => {
  return (
    <html lang="en">
      <body className="bg-slate-100 ">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
};
export default RootLayout;
